#ifndef MUDDY_CONFIG_HPP_INCLUDED_
#define MUDDY_CONFIG_HPP_INCLUDED_

#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_TR1_MEMORY 1
#cmakedefine HAVE_IN_ADDR_T 1
#cmakedefine HAVE_WINSOCK2_H 1

#endif // MUDDY_CONFIG_HPP_INCLUDED_
