set(CMAKE_SYSTEM_NAME Windows)
set(MUDDY_TOOLCHAIN_PREFIX x86_64-w64-mingw32- CACHE STRING
		"Cross compiling toolchain prefix, must ends with a dash(-)")
set(CMAKE_C_COMPILER ${MUDDY_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${MUDDY_TOOLCHAIN_PREFIX}g++)

if (CMAKE_HOST_WIN32)
	set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}.exe")
	set(CMAKE_CXX_COMPILER "${CMAKE_CXX_COMPILER}.exe")
endif()

execute_process(COMMAND ${MUDDY_TOOLCHAIN_PREFIX}gcc -print-sysroot
		OUTPUT_VARIABLE CMAKE_FIND_ROOT_PATH
		OUTPUT_STRIP_TRAILING_WHITESPACE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
